MvcProjeKampi/Areas/Writer/Controllers/WriterPanelContentController.cs
using BusinessLayer.Concrate;
using DataAccessLayer.Concrate;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Areas.Writer.Controllers
{
    public class WriterPanelContentController : Controller
    {
        ContentManager cm = new ContentManager(new EfContentDal());
        Context c = new Context();
        // GET: Writer/WriterPanelContent
        public ActionResult MyContent(string p)
        {
            p = (string)Session["WriterMail"];
            var writeridinfo = c.Writers.Where(x => x.WriterMail == p).Select(y => y.WriterID).FirstOrDefault();

            var contentvalues = cm.GetListByWriter(writeridinfo);
            return View(contentvalues);
        }
        public ActionResult MyContentDetails(int id)
        {
            //var contentvalues = cm.GetListByContent(id);
            //return View(contentvalues);

            //string p = (string)Session["WriterMail"];

            //id = c.Writers.Where(x => x.WriterMail == p).Select(y => y.WriterID).FirstOrDefault();
            var writervalue = c.Contents.Where(x => x.ContentID == id).ToList();

            return View(writervalue);
        }

        [HttpGet]
        public ActionResult EditContent(int id)
        {
            ViewBag.d = id;
            return View();
        }
        [HttpPost]
        public ActionResult EditContent(Content p)
        {
            string mail = (string)Session["WriterMail"];
            var writeridinfo = c.Writers.Where(x => x.WriterMail == mail).Select(y => y.WriterID).FirstOrDefault();

            p.ContentDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            p.WriterID = writeridinfo;
            p.ContentStatus = true;
            cm.ContentAdd(p);
            return RedirectToAction("MyContent");
        }


        [HttpGet]
        public ActionResult AddContent(int id)
        {
            ViewBag.d = id;
            return View();
        }
        [HttpPost]
        public ActionResult AddContent(Content p)
        {
            string mail = (string)Session["WriterMail"];
            var writeridinfo = c.Writers.Where(x => x.WriterMail == mail).Select(y => y.WriterID).FirstOrDefault();

            p.ContentDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            p.WriterID = writeridinfo;
            p.ContentStatus = true;
            cm.ContentAdd(p);
            return RedirectToAction("MyContent");
        }

        public ActionResult ToDoList()
        {
            return View();
        }
    }
}

MvcProjeKampi/Areas/Writer/Views/WriterPanelContent/AddContent.cshtml
@model EntityLayer.Concrete.Content

@{
    ViewBag.Title = "AddContent";
    Layout = "~/Areas/Writer/Views/Shared/_WriterLayout.cshtml";
}
<script src="~/AdminLT/assets/bundles/lib.vendor.bundle.js"></script>
<script src="~/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- summernote -->
<link rel="stylesheet" href="~/AdminLTE/plugins/summernote/summernote-bs4.css">

<script src="~/AdminLTE/plugins/summernote/summernote.min.js"></script>
<h1>İçerik Girişi</h1>
<br />
@using (Html.BeginForm("AddContent", "WriterPanelContent", "Writer", FormMethod.Post))
{
    <div class="form-group">
        <input type="hidden" name="HeadingID" value="@ViewBag.d" />
        @Html.Label("İçeriğinizi Yazın")
        <div class="form-group">
            <textarea id="compose-textarea" name="ContentValue" class="form-control">
        </textarea>
        </div>
        @Html.ValidationMessageFor(x => x.ContentValue)
        <br />
        @Html.Label("Resim1 Yolu")
        @Html.TextBoxFor(x => x.ImageUrl1, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ImageUrl1)
        <br />
        @Html.Label("Resim2 Yolu")
        @Html.TextBoxFor(x => x.ImageUrl2, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ImageUrl2)
        <br />
        @Html.Label("Resim3 Yolu")
        @Html.TextBoxFor(x => x.ImageUrl3, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ImageUrl3)
        <br />

        <button class="btn btn-info">Başlığı Oluştur</button>
    </div>
}


<!-- /.content -->
<!-- /.content-wrapper -->
<!-- Control Sidebar -->
<!-- /.control-sidebar -->
<!-- ./wrapper -->
<!-- jQuery -->
<script src="~/AdminLTE/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="~/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="~/AdminLTE/dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="~/AdminLTE/dist/js/demo.js"></script>
<!-- Summernote -->
<script src="~/AdminLTE/plugins/summernote/summernote-bs4.min.js"></script>
<!-- Page Script -->
<script>
    $(function () {
        //Add text editor
        $('#compose-textarea').summernote()
    })</script>

MvcProjeKampi/Areas/Writer/Views/WriterPanelContent/MyContent.cshtml
@using EntityLayer.Concrete
@model  List<Content>

@{
    ViewBag.Title = "MyContent";
    Layout = "~/Areas/Writer/Views/Shared/_WriterLayout.cshtml";
}
<script src="~/AdminLT/assets/bundles/lib.vendor.bundle.js"></script>
<script src="~/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->



                        <div class="timeline">
                            <!-- timeline time label -->
                            @foreach (var item in Model)
                            {
                                <div class="time-label">
                                    <span class="bg-success">@item.ContentDate.ToLongDateString()</span>
                                </div>
                                <!-- /.timeline-label -->
                                <!-- timeline item -->
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@item.Heading.HeadingName</a></h3>
                                        <div class="timeline-body">
                                            @item.ContentValue
                                        </div>
                                    </div>
                                </div>
                                <!-- END timeline item -->
                            }
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>

MvcProjeKampi/Areas/Writer/Views/WriterPanelContent/MyContentDetails.cshtml
@*@using EntityLayer.Concrete
    @model List<Content>*@
@model EntityLayer.Concrete.Content
@{
    ViewBag.Title = "MyContentDetails";
    Layout = "~/Areas/Writer/Views/Shared/_WriterLayout.cshtml";
}
<script src="~/AdminLT/assets/bundles/lib.vendor.bundle.js"></script>
<script src="~/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->



                        <div class="timeline">
                            <!-- timeline time label -->
                           
                                <div class="time-label">
                                    <span class="bg-success">@Html.DisplayFor(x=>x.ContentDate.ToLongDateString())</span>
                                </div>
                                <!-- /.timeline-label -->
                                <!-- timeline item -->
                                <div>
                                    <a class="fas fa-comment bg-yellow" href="/WriterPanelontent/MyContentDetails/"><i @*class="fas fa-comment bg-yellow"*@></i></a>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@Html.DisplayFor(x=>x.Heading.HeadingName)</a></h3>
                                        <div class="timeline-body">
                                            @Html.DisplayFor(x => x.ContentValue)
                                        </div>
                                    </div>
                                </div>
                    
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>

MvcProjeKampi/Areas/Writer/Views/WriterPanelContent/ToDoList.cshtml
@{
    ViewBag.Title = "ToDoList";
    Layout = "~/Areas/Writer/Views/Shared/_WriterLayout.cshtml";
}

<p><del>#1 Profilim Sayfası</del></p>
<p><del>#2 Tüm Başlıklarda Paging </del></p>
<p><del>#3 Mesajlarda Session</del></p>
<p><del>#4 Oturum yönetiminin mimariye taşınması</del></p>
<p>#5 Token Kullanımı</p>