MvcProjeKampi/Areas/Admin/Controllers/AdminAuthorizationController.cs
using BusinessLayer.Concrate;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Areas.Admin.Controllers
{
    [Authorize]
    public class AdminAuthorizationController : Controller
    {
        AdminManager adminmanager = new AdminManager(new EfAdminDal());
        // GET: Admin/AdminAuthorization
        public ActionResult Index()
        {
            var adminvalues = adminmanager.GetList();
            return View(adminvalues);
        }
        [HttpGet]
        public ActionResult AddAdmin()
        {
            List<SelectListItem> valuerole = (from x in adminmanager.GetList()
                                              select new SelectListItem
                                              {
                                                  Text = x.AdminRole,
                                                  Value = x.AdminID.ToString()
                                              }).ToList();

            ViewBag.vlc = valuerole;
            return View();
        }
        [HttpPost]
        public ActionResult AddAdmin(AdminUser p)
        {
            p.AdminStatus = true;
            p.AdminRole = ViewBag.vlc;
            adminmanager.AdminAdd(p);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditAdmin(int id)
        {//böylece ıd değişkeninden gelen parametre değerine göre ilgili satırın kayıtlarını categoryvalue
         //isimli değişkene atadık
            List<SelectListItem> valuerole = (from x in adminmanager.GetList()
                                              select new SelectListItem
                                              {
                                                  Text = x.AdminRole,
                                                  Value = x.AdminID.ToString()
                                              }).ToList();

            ViewBag.vlc = valuerole;

            var adminvalue = adminmanager.GetByID(id);
            return View(adminvalue);
        }
        [HttpPost]
        public ActionResult EditAdmin(AdminUser p)
        {
            adminmanager.AdminUpdate(p);
            return RedirectToAction("Index");
        }

        public ActionResult Active(int id)
        {
            var deger = adminmanager.GetByID(id);
            deger.AdminStatus = true;
            adminmanager.AdminUpdate(deger);
            return RedirectToAction("Index");
        }
        public ActionResult DeActive(int id)
        {
            var deger = adminmanager.GetByID(id);
            deger.AdminStatus = false;
            adminmanager.AdminUpdate(deger);
            return RedirectToAction("Index");
        }

    }
}

MvcProjeKampi/Areas/Admin/Views/AdminAuthorization/AddAdmin.cshtml
@model EntityLayer.Concrete.AdminUser
@{
    ViewBag.Title = "AddAdmin";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<script src="~/AdminLT/assets/bundles/lib.vendor.bundle.js"></script>
<script src="~/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<h1>Yeni Admin Eklme Sayfası</h1>
<br />
@using (Html.BeginForm("AddAdmin", "AdminAuthorization", "Admin", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Admin Kullanıcı Adı")
        @Html.TextBoxFor(x => x.AdminUserName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.AdminUserName)
        <br />
        @Html.Label("Şifre Giriniz")
        @Html.PasswordFor(x => x.AdminUserPassword, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.AdminUserPassword)
        <br />
        @*@Html.Label("Rolü Seçiniz")
            @Html.TextBoxFor(x => x.AdminRole, new { @class = "form-control" })
            <br />*@
        @Html.Label("Admin Rolü")
        @Html.DropDownListFor(x => x.AdminID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        <br />
        <button class="btn btn-primary">Ekle</button>
    </div>
}

MvcProjeKampi/Areas/Admin/Views/AdminAuthorization/EditAdmin.cshtml
@model EntityLayer.Concrete.AdminUser
@{
    ViewBag.Title = "EditAdmin";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<script src="~/AdminLT/assets/bundles/lib.vendor.bundle.js"></script>
<script src="~/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<br />
<h2>Admin Güncelleme Sayfası</h2>

@using (Html.BeginForm("EditAdmin", "AdminAuthorization", "Admin", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.AdminID, new { @class = "form-control" })

        @Html.Label("Admin Kullanıcı Adı")
        @Html.TextBoxFor(x => x.AdminUserName, new { @class = "form-control" })
        <br />
        @Html.Label("Admin Şifre")
        @Html.TextBoxFor(x => x.AdminUserPassword, new { @class = "form-control" })
        <br />
        @*@Html.Label("Admin Rolü")
            @Html.TextBoxFor(x => x.AdminRole, new { @class = "form-control" })
            <br />*@
        @Html.Label("Admin Rolü")
        @Html.DropDownListFor(x => x.AdminID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}

MvcProjeKampi/Areas/Admin/Views/AdminAuthorization/Index.cshtml
@using EntityLayer.Concrete
@model List<AdminUser>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<script src="~/AdminLT/assets/bundles/lib.vendor.bundle.js"></script>
<script src="~/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<h3>Adminler</h3>
<br />

<div class="section-body">
    <div class="container-fluid">
        <div class="tab-content taskboard">
            <div class="tab-pane fade show active" id="TaskBoard-list" role="tabpanel">
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table table-hover table-vcenter mb-0 table_custom spacing8 text-nowrap">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Admin Mail</th>
                                        <th>Yetki</th>
                                        <th>Status</th>
                                        <th>Pasif Yap</th>
                                        <th>Yetkisini Değiştir</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <th>@item.AdminID</th>
                                            <td>@item.AdminUserName</td>
                                            <td>@item.AdminRole</td>
                                            <td>Aktif</td>
                                            <td><a href="/Admin/AdminAuthorization/DeActive/@item.AdminID" class="btn btn-danger">Pasif Yap</a></td>
                                            <td><a href="/Admin/AdminAuthorization/EditAdmin/@item.AdminID" class="btn btn-warning">Yetkisini Değiştir</a></td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <a href="/Admin/AdminAuthorization/AddAdmin" class="btn btn-info">Yeni Admin Tanımla</a>
        </div>
    </div>
</div>