MvcProjeKampi/Areas/Admin/Controllers/AdminChartController.cs
using BusinessLayer.Concrate;
using DataAccessLayer.Concrate;
using DataAccessLayer.EntityFramework;
using MvcProjeKampi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Areas.Admin.Controllers
{
    [Authorize]
    public class AdminChartController : Controller
    {
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        Context c = new Context();
        // GET: Admin/AdminChart
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CategoryChart()
        {
            return Json(BlogList(), JsonRequestBehavior.AllowGet);
        }

        public List<CategoryClass> BlogList()
        {
            List<CategoryClass> cs2 = new List<CategoryClass>();
            using (var c = new Context())
            {
                cs2 = c.Categories.Select(x => new CategoryClass
                {
                    CategoryName = x.CategoryName,
                    CategoryCount = x.CategoryID
                }).ToList();
            }
            return cs2;
        }

        //----------------
        public ActionResult Index2()
        {
            return View();
        }

        public ActionResult HeadingChart()
        {
            return Json(HeadingList(), JsonRequestBehavior.AllowGet);
        }

        public List<HeadingClass> HeadingList()
        {
            List<HeadingClass> cs2 = new List<HeadingClass>();
            using (var c = new Context())
            {
                cs2 = c.Headings.Select(x => new HeadingClass
                {
                    HeadingName = x.HeadingName,
                    HeadingCount = x.HeadingID
                }).ToList();
            }
            return cs2;

        }
    }
}

MvcProjeKampi/Areas/Admin/Views/AdminChart/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("CategoryChart", "AdminChart","Admin")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Kategori Adı');
            data.addColumn('number', 'Kategori Sayısı');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.CategoryName, obj.CategoryCount]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                width: 1000,
                height: 800,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart
                (document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <h2>Kategori Başlık Grafiği</h2>
    <div id="Piechart_div"></div>
</body>
</html>

MvcProjeKampi/Areas/Admin/Views/AdminChart/Index2.cshtml
@{
    ViewBag.Title = "Index2";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
            $(document).ready(function () {
                $.ajax({
                    type: "POST",
                    dataType: "json",
                    contentType: "application/json",
                    url: '@Url.Action("HeadingChart", "AdminChart","Admin")',
                    success: function (result) {
                        google.charts.load('current', {
                            'packages': ['corechart']
                        });
                        google.charts.setOnLoadCallback(function () {
                            drawChart(result);
                        });
                    }
                });
            });

            function drawChart(result) {
                var data = new google.visualization.DataTable();
                data.addColumn('string', 'Başlık Adı');
                data.addColumn('number', 'Başlık Sayısı');
                var dataArray = [];

                $.each(result, function (i, obj) {
                    dataArray.push([obj.HeadingName, obj.HeadingCount]);
                });
                data.addRows(dataArray);

                var columnChartOptions = {
                    width: 1000,
                    height: 800,
                    bar: { groupWidth: "20%" },
                };

                var columnChart = new google.visualization.LineChart
                    (document
                    .getElementById('Piechart_div'));

                columnChart.draw(data, columnChartOptions);
            }
    </script>
</head>
<body>
    <h2>Başlık - Yazı Grafiği</h2>
    <div id="Piechart_div"></div>
</body>
</html>